data:
  dataset_name: ai4bharat/IndicVoices
  language: punjabi

  split_train: train
  split_val_candidates:
    - validation
    - valid
    - test

  audio_column: audio
  text_candidates:
    - normalized
    - text
    - verbatim
  domain_column: task_name

  sampling_rate: 16000
  min_duration_secs: 1.0
  max_duration_secs: 30.0

  shuffle_buffer_size: 500
  prefetch_size: 8
  seed: 42

model:
  processor_name: openai/whisper-small

batching:
  train_batch_size: 16
  eval_batch_size: 8
  max_label_length: 256