model:
  name: openai/whisper-large-v3
  language: punjabi
  task: transcribe

training:
  output_dir: checkpoints
  max_steps: 30000
  warmup_steps: 1000

  per_device_train_batch_size: 16
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 4

  learning_rate: 5.0e-6
  lr_scheduler_type: linear
  weight_decay: 0.01

  eval_strategy: steps
  eval_steps: 2000
  save_strategy: steps
  save_steps: 2000
  save_total_limit: 3

  load_best_model_at_end: true
  metric_for_best_model: wer
  greater_is_better: false

  bf16: true
  fp16: false
  gradient_checkpointing: true
  dataloader_num_workers: 0
  dataloader_pin_memory: false

  predict_with_generate: true
  generation_max_length: 448
  logging_steps: 50
  report_to: none
  smoke_test_steps: 10